default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inteva_api_development
  username: inteva_user
  password: inteva_user

test:
  <<: *default
  database: inteva_api_test
  username: inteva_user
  password: inteva_user

production:
  <<: *default
  database: inteva_api_production
  username: inteva_user
  password: inteva_user
